In [1]:
# Step 1 - Import Libraries

import numpy as np
import pandas as pd

In [2]:
# Step 2 - Load Dataset

def load_fitness_data(file_path):
    try:
        # Read CSV file
        df = pd.read_csv(file_path)

        # Store Date column separately
        dates = df["Date"].tolist()

        # Convert numeric columns to NumPy array
        data = df[["Steps", "SleepHours", "CaloriesBurned"]].to_numpy()

        print("Dataset Loaded Successfully!")
        print("Shape of Dataset:", data.shape)

        return dates, data

    except Exception as e:
        print("Error loading dataset:", e)
        return None, None

In [3]:
# Dataset URL
file_path = "https://samatrix-data.s3.ap-south-1.amazonaws.com/Statistics-Project/fitness_data.csv"

# Load Data
dates, data = load_fitness_data(file_path)

# Display first 5 dates
print(dates[:5])

# Display first 5 rows
print(data[:5])

Dataset Loaded Successfully!
Shape of Dataset: (30, 3)
['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04', '2025-05-05']
[[1.1656e+04 8.1000e+00 2.6690e+03]
 [4.9070e+03 9.0000e+00 2.4700e+03]
 [7.4060e+03 7.5000e+00 1.7120e+03]
 [1.1961e+04 6.5000e+00 2.7370e+03]
 [1.2692e+04 8.5000e+00 1.5090e+03]]


In [4]:
# Step 3 - Weekly Analysis

def weekly_analysis(data, week_number):
    start = (week_number - 1) * 7
    end = start + 7

    week_data = data[start:end]

    avg = np.mean(week_data, axis=0)

    print(f"\n===== Week {week_number} =====")
    print(f"Average Steps       : {avg[0]:.2f}")
    print(f"Average Sleep Hours : {avg[1]:.2f}")
    print(f"Average Calories    : {avg[2]:.2f}")

    return week_data

In [5]:
# Run Weekly Analysis

for week in range(1, 5):
    weekly_analysis(data, week)


===== Week 1 =====
Average Steps       : 9040.57
Average Sleep Hours : 7.44
Average Calories    : 2156.57

===== Week 2 =====
Average Steps       : 9801.57
Average Sleep Hours : 6.66
Average Calories    : 2088.29

===== Week 3 =====
Average Steps       : 9961.14
Average Sleep Hours : 5.51
Average Calories    : 1914.14

===== Week 4 =====
Average Steps       : 11135.71
Average Sleep Hours : 6.39
Average Calories    : 2220.29


In [6]:
# Step 4 - Find Low Activity Days

def find_low_activity_days(data, dates):

    print("\n===== Low Activity Days =====")

    low_steps = data[:, 0] < 6000
    low_sleep = data[:, 1] < 6
    low_calories = data[:, 2] < 1800

    found = False

    for i in range(len(data)):
        if low_steps[i] or low_sleep[i] or low_calories[i]:
            found = True
            print(f"\nDate: {dates[i]}")
            print(f"Steps: {data[i,0]}")
            print(f"Sleep Hours: {data[i,1]}")
            print(f"Calories Burned: {data[i,2]}")

    if not found:
        print("No low activity days found.")

In [7]:
find_low_activity_days(data, dates)


===== Low Activity Days =====

Date: 2025-05-02
Steps: 4907.0
Sleep Hours: 9.0
Calories Burned: 2470.0

Date: 2025-05-03
Steps: 7406.0
Sleep Hours: 7.5
Calories Burned: 1712.0

Date: 2025-05-05
Steps: 12692.0
Sleep Hours: 8.5
Calories Burned: 1509.0

Date: 2025-05-06
Steps: 4249.0
Sleep Hours: 6.8
Calories Burned: 1519.0

Date: 2025-05-07
Steps: 10413.0
Sleep Hours: 5.7
Calories Burned: 2480.0

Date: 2025-05-09
Steps: 5763.0
Sleep Hours: 8.9
Calories Burned: 2766.0

Date: 2025-05-10
Steps: 4550.0
Sleep Hours: 5.3
Calories Burned: 2131.0

Date: 2025-05-11
Steps: 12958.0
Sleep Hours: 7.0
Calories Burned: 1575.0

Date: 2025-05-13
Steps: 13808.0
Sleep Hours: 4.9
Calories Burned: 1854.0

Date: 2025-05-14
Steps: 8703.0
Sleep Hours: 4.8
Calories Burned: 1526.0

Date: 2025-05-15
Steps: 10273.0
Sleep Hours: 5.7
Calories Burned: 1648.0

Date: 2025-05-16
Steps: 8386.0
Sleep Hours: 4.5
Calories Burned: 2451.0

Date: 2025-05-17
Steps: 11035.0
Sleep Hours: 5.6
Calories Burned: 1623.0

Date: 2025-05

In [8]:
# Step 5 - Daily Fitness Score

def fitness_score(day):

    steps, sleep, calories = day

    step_score = min(steps / 10000, 1)
    sleep_score = min(sleep / 8, 1)
    calorie_score = min(calories / 2200, 1)

    score = (0.4 * step_score) + (0.3 * sleep_score) + (0.3 * calorie_score)

    return round(score * 100, 2)

In [9]:
print("Fitness Score of Day 1:", fitness_score(data[0]))

Fitness Score of Day 1: 100.0


In [10]:
# Step 6 - Score Every Day

def score_all_days(data):
    scores = []

    for day in data:
        scores.append(fitness_score(day))

    return np.array(scores)

In [11]:
scores = score_all_days(data)

print("All Fitness Scores:")
print(scores)

All Fitness Scores:
[100.    79.63  81.09  94.38  90.58  63.21  91.38  97.31  83.05  67.13
  87.73  95.88  83.66  73.62  83.85  80.42  83.13  92.13  71.1   67.55
  85.78  80.    92.34  88.41  97.04  88.75  95.88  84.34  66.02  85.43]


In [12]:
# Step 7 - Monthly Summary

def monthly_summary(data, dates):

    print("\n========== MONTHLY SUMMARY ==========")

    best_day = np.argmax(data[:,0])
    worst_day = np.argmin(data[:,0])

    print(f"\nBest Step Day : {dates[best_day]}")
    print(f"Steps : {data[best_day,0]}")

    print(f"\nWorst Step Day : {dates[worst_day]}")
    print(f"Steps : {data[worst_day,0]}")

    scores = score_all_days(data)

    top3 = np.argsort(scores)[-3:][::-1]

    print("\nTop 3 Fitness Days")

    for i in top3:
        print(f"{dates[i]} ---> Score : {scores[i]}")

In [13]:
monthly_summary(data, dates)


========== MONTHLY SUMMARY ==========

Best Step Day : 2025-05-21
Steps : 14839.0

Worst Step Day : 2025-05-29
Steps : 4224.0

Top 3 Fitness Days
2025-05-01 ---> Score : 100.0
2025-05-08 ---> Score : 97.31
2025-05-25 ---> Score : 97.04


In [14]:
# Step 8 - Save Summary Report

def save_summary(data):

    active_days = np.sum(data[:,0] >= 10000)

    avg_sleep = np.mean(data[:,1])

    avg_calories = np.mean(data[:,2])

    with open("fitness_summary.txt","w") as file:

        file.write("FITNESS TRACKER SUMMARY\n")
        file.write("=======================\n\n")

        file.write(f"Active Days : {active_days}\n")
        file.write(f"Average Sleep : {avg_sleep:.2f} Hours\n")
        file.write(f"Average Calories Burned : {avg_calories:.2f}\n")

    print("\nfitness_summary.txt saved successfully.")

In [15]:
save_summary(data)


fitness_summary.txt saved successfully.


In [16]:
print("\n========= FITNESS TRACKER PROJECT =========")

if data is not None:

    for week in range(1,5):
        weekly_analysis(data, week)

    find_low_activity_days(data, dates)

    monthly_summary(data, dates)

    save_summary(data)

else:
    print("Dataset could not be loaded.")


========= FITNESS TRACKER PROJECT =========

===== Week 1 =====
Average Steps       : 9040.57
Average Sleep Hours : 7.44
Average Calories    : 2156.57

===== Week 2 =====
Average Steps       : 9801.57
Average Sleep Hours : 6.66
Average Calories    : 2088.29

===== Week 3 =====
Average Steps       : 9961.14
Average Sleep Hours : 5.51
Average Calories    : 1914.14

===== Week 4 =====
Average Steps       : 11135.71
Average Sleep Hours : 6.39
Average Calories    : 2220.29

===== Low Activity Days =====

Date: 2025-05-02
Steps: 4907.0
Sleep Hours: 9.0
Calories Burned: 2470.0

Date: 2025-05-03
Steps: 7406.0
Sleep Hours: 7.5
Calories Burned: 1712.0

Date: 2025-05-05
Steps: 12692.0
Sleep Hours: 8.5
Calories Burned: 1509.0

Date: 2025-05-06
Steps: 4249.0
Sleep Hours: 6.8
Calories Burned: 1519.0

Date: 2025-05-07
Steps: 10413.0
Sleep Hours: 5.7
Calories Burned: 2480.0

Date: 2025-05-09
Steps: 5763.0
Sleep Hours: 8.9
Calories Burned: 2766.0

Date: 2025-05-10
Steps: 4550.0
Sleep Hours: 5.3
Calori

# Conclusion

This Fitness Tracker project was developed using Python, NumPy, and Pandas to analyze daily fitness data. The project successfully loads the dataset, calculates weekly averages, identifies low activity days, generates daily fitness scores, and provides a monthly summary. It also creates a text report containing important health statistics.

The project helps users understand their fitness performance and identify areas where improvement is needed. In the future, this project can be enhanced by adding graphs, user input options, and a graphical user interface to make it more interactive and user-friendly.

1. The project works only with one CSV dataset.
2. No graphical visualization is included.
3. Daily targets are fixed and cannot be changed by the user.
4. No GUI is available.

1. Add charts using Matplotlib.
2. Allow users to upload their own fitness data.
3. Create a GUI using Tkinter.
4. Generate PDF reports automatically.
5. Add BMI and water intake tracking.

# Fitness Tracker Project

## Step 1 - Import Libraries

## Step 2 - Load Dataset

## Step 3 - Weekly Analysis

## Step 4 - Low Activity Days

## Step 5 - Daily Fitness Score

## Step 6 - Score Every Day

## Step 7 - Monthly Summary

## Step 8 - Save Summary Report

## Step 9 - Main Program

## Step 10 - Conclusion